### ISSUE TITLE
AngioTool-Batch will only run once on Windows 10 Pro

### ISSUE THREAD

**Issue by papadirky** [jbendtsen/AngioTool-Batch#1]
I am having trouble with AngioTool-Batch. I installed it on two different PCs with Windows 10 Pro (version 22H2), JAVA Version 8, Update 321. It will run the first time, but not a second time. After you quit the program once, it will never start again. No reason given. Don't know what else to try. 
Thanks for checking

**Comment by jbendtsen** [comment]
Thank you for bringing this to my attention. Which version from the releases tab did you download?

**Comment by jbendtsen** [comment]
I was able to reproduce the issue. There was a method that was calling String.strip(), which does not exist in Java 8. This issue, along with a few others, have now been fixed in the latest release.
